export const genderlist = [
  { id: "m", body: "m" },
  { id: "f", body: "f" },

]


export const islands = [{ id: "malecity.male", body: "މާލެ ސިޓީ. މާލެ" },
{ id: "malecity.vilingili", body: "މާލެ ސިޓީ. ވިލިނގިލި" },
{ id: "malecity.hulhumaale", body: "މާލެ ސިޓީ. ހުޅުމާލެ" },
{ id: "fuvahmulahcity.fuvahmulah", body: "ފުވައްމުލައް ސިޓީ. ފުވައްމުލައް" },
{ id: "adducity.meedhoo", body: "އައްޑޫ ސިޓީ. މީދޫ" },
{ id: "adducity.hithadhoo", body: "އައްޑޫ ސިޓީ. ހިތަދޫ" },
{ id: "adducity.maradhoo", body: "އައްޑޫ ސިޓީ. މަރަދޫ" },
{ id: "adducity.feydhoo", body: "އައްޑޫ ސިޓީ. ފޭދޫ" },
{ id: "adducity.maradhoofeydhoo", body: "އައްޑޫ ސިޓީ. މަރަަދޫ ފޭދޫ" },
{ id: "adducity.hulhudhoo", body: "އައްޑޫ ސިޓީ. ހިތަަދޫ" },
{ id: "kulhudhuffushicity.kulhudhuffushi", body: "ކުޅުދުއްފުށި ސިޓީ. ކުޅުދުއްފުށި" },
{ id: "aa.bodufolhudhoo", body: "އއ. ބޮޑުފޮޅުދޫ" },
{ id: "aa.feridhoo", body: "އއ. ފެރިދޫ" },
{ id: "aa.himendhoo", body: "އއ. ހިމަންދޫ" },
{ id: "aa.maalhos", body: "އއ. މާޅޮސް" },
{ id: "aa.mathiveri", body: "އއ. މަތިވެރި" },
{ id: "aa.rasdhoo", body: "އއ. ރަސްދޫ" },
{ id: "aa.thoddoo", body: "އއ. ތޮއްޑޫ" },
{ id: "aa.ukulhas", body: "އއ. އުކުޅަސް" },
{ id: "adh.dhangethi", body: "އދ. ދަނގެތި" },
{ id: "adh.dhigurah", body: "އދ. ދިގުރަށް" },
{ id: "adh.dhihdhoo", body: "އދ. ދިއްދޫ" },
{ id: "adh.fenfushi", body: "އދ. ފެންފުށި" },
{ id: "adh.hangnaameedhoo", body: "އދ. ހަންޏާމީދޫ" },
{ id: "adh.kunburudhoo", body: "އދ. ކުނބުރުދޫ" },
{ id: "adh.maamingili", body: "އދ. މާމިގިލި" },
{ id: "adh.mahibadhoo", body: "އދ. މަހިބަދޫ" },
{ id: "adh.mandhoo", body: "އދ. މަންދޫ" },
{ id: "adh.omadhoo", body: "އދ. އޮމަދޫ" },
{ id: "b.dharavandhoo", body: "ބ. ދަރަވަންދޫ" },
{ id: "b.dhonfanu", body: "ބ. ދަޮންފަނު" },
{ id: "b.eydhafushi", body: "ބ. އޭދަފުށި" },
{ id: "b.fehendhoo", body: "ބ. ފެހެންދޫ" },
{ id: "b.fulhadhoo", body: "ބ. ފުޅަދޫ" },
{ id: "b.goidhoo", body: "ބ. ގޮއިދޫ" },
{ id: "b.hithaadhoo", body: "ބ. ހިތާދޫ" },
{ id: "b.kamadhoo", body: "ބ. ކަމަދޫ" },
{ id: "b.kendhoo", body: "ބ. ކެންދޫ" },
{ id: "b.kihaadhoo", body: "ބ. ކިހާދޫ" },
{ id: "b.kudarikilu", body: "ބ. ކުޑަރިކިލު" },
{ id: "b.maalhos", body: "ބ. މާޅޮސް" },
{ id: "b.thulhaadhoo", body: "ބ. ތުޅާދޫ" },
{ id: "dh.bandidhoo", body: "ދ. ބަނޑިދޫ" },
{ id: "dh.hulhudheli", body: "ދ. ހުޅުދެލި" },
{ id: "dh.gemendhoo", body: "ދ. ގެމެންދޫ" },
{ id: "dh.kudahuvadhoo", body: "ދ. ކުޑަހުވަދޫ" },
{ id: "dh.maaenboodhoo", body: "ދ. މާއެނބޫދޫ" },
{ id: "dh.meedhoo", body: "ދ. މީދޫ" },
{ id: "dh.rinbudhoo", body: "ދ. ރިނބުދޫ" },
{ id: "f.bileiydhoo", body: "ފ. ބިލެތްދޫ" },
{ id: "f.dharanboodhoo", body: "ފ. ދަރަނބޫދޫ" },
{ id: "f.feeali", body: "ފ. ފީއަލި" },
{ id: "f.magoodhoo", body: "ފ. މަގޫދޫ" },
{ id: "f.nilandhoo", body: "ފ. ނިލަންދޫ" },
{ id: "ga.dhaandhoo", body: "ގއ. ދާންދޫ" },
{ id: "ga.dhevvadhoo", body: "ގއ. ދެއްވަދޫ" },
{ id: "ga.dhiyadhoo", body: "ގއ. ދިޔަދޫ" },
{ id: "ga.gemanafushi", body: "ގއ. ގެމަނަފުށި" },
{ id: "ga.kanduhulhudhoo", body: "ގއ. ކަނޑުހުޅުދޫ" },
{ id: "ga.kolamaafushi", body: "ގއ. ކޮލަމާފުށި" },
{ id: "ga.kondey", body: "ގއ. ކޮނޑޭ" },
{ id: "ga.maamendhoo", body: "ގއ. މާމެންދޫ" },
{ id: "ga.nilandhoo", body: "ގއ. ނިލަންދޫ" },
{ id: "ga.vilingili", body: "ގއ. ވިލިނގިލި" },
{ id: "gdh.faresmaathodaa", body: "ގދ. ފަރެސްމާތޮޑާ" },
{ id: "gdh.fiyoari", body: "ގދ. ފިޔޯރީ" },
{ id: "gdh.gahdhoo", body: "ގދ. ގައްދޫ" },
{ id: "gdh.hoandehdhoo", body: "ގދ. ހޯނޑެއްދޫ" },
{ id: "gdh.madaveli", body: "ގދ. މަޑަވެލި" },
{ id: "gdh.nadellaa", body: "ގދ. ނަޑެއްލާ" },
{ id: "gdh.rathafandhoo", body: "ގދ. ރަތަފަންދޫ" },
{ id: "gdh.thinadhoo", body: "ގދ. ތިނަދޫ" },
{ id: "gdh.vaadhoo", body: "ގދ. ވާދޫ" },
{ id: "ha.baarah", body: "ހއ. ބާރަށް" },
{ id: "ha.dhidhdhoo", body: "ހއ. ދިއްދޫ" },
{ id: "ha.filladhoo", body: "ހއ. ފިއްލަދޫ" },
{ id: "ha.hoarafushi", body: "ހއ. ހޯރަފުށި" },
{ id: "ha.ihavandhoo", body: "ހއ. އިހަވަންދޫ" },
{ id: "ha.kelaa", body: "ހއ. ކެލާ" },
{ id: "ha.maarandhoo", body: "ހއ. މާރަންދޫ" },
{ id: "ha.molhadhoo", body: "ހއ. މޮޅަދޫ" },
{ id: "ha.muraidhoo", body: "ހއ. މުރައިދޫ" },
{ id: "ha.thakandhoo", body: "ހއ. ތަކަންދޫ" },
{ id: "ha.thuraakunu", body: "ހއ. ތުރާކުނު" },
{ id: "ha.uligamu", body: "ހއ. އުލިގަމު" },
{ id: "ha.utheemu", body: "ހއ. އުތީމު" },
{ id: "ha.vashafaru", body: "ހއ. ވަށަފަރު" },
{ id: "hdh.finey", body: "ހދ. ފިނޭ" },
{ id: "hdh.hanimaadhoo", body: "ހދ. ހަނިމާދޫ" },
{ id: "hdh.hirimaradhoo", body: "ހދ. ހިރިމަރަދޫ" },
{ id: "hdh.kumundhoo", body: "ހދ. ކުމުންދޫ" },
{ id: "hdh.kurinbi", body: "ހދ. ކުރިނބި" },
{ id: "hdh.kunburudhoo", body: "ހދ. ކުނބުރުދޫ" },
{ id: "hdh.maavaidhoo", body: "ހދ. މާވައިދޫ" },
{ id: "hdh.makunudhoo", body: "ހދ. މަކުނުދޫ" },
{ id: "hdh.naivaadhoo", body: "ހދ. ނައިވާދޫ" },
{ id: "hdh.nellaidhoo", body: "ހދ. ނެއްލައިދޫ" },
{ id: "hdh.neykurendhoo", body: "ހދ. ނޭކުރެންދޫ" },
{ id: "hdh.nolhivaram", body: "ހދ. ނޮޅިވަރަން" },
{ id: "hdh.nolhivaranfaru", body: "ހދ. ނޮޅިވަރަންފަރު" },
{ id: "hdh.vaikaradhoo", body: "ހދ. ވައިކަރަދޫ" },
{ id: "k.dhiffushi", body: "ކ. ދިއްފުށި" },
{ id: "k.gaafaru", body: "ކ. ގާފަރު" },
{ id: "k.gulhi", body: "ކ. ގުޅި" },
{ id: "k.guraidhoo", body: "ކ. ގުރައިދޫ" },
{ id: "k.hinmafushi", body: "ކ. ހިންމަފުށި" },
{ id: "k.huraa", body: "ކ. ހުރާ" },
{ id: "k.kaashidhoo", body: "ކ. ކާށިދޫ" },
{ id: "k.maafushi", body: "ކ. މާފުށި" },
{ id: "k.thulusdhoo", body: "ކ. ތުލުސްދޫ" },
{ id: "l.dhanbidhoo", body: "ލ. ދަނބިދޫ" },
{ id: "l.fonadhoo", body: "ލ. ފޮނަދޫ" },
{ id: "l.gaadhoo", body: "ލ. ގާދޫ" },
{ id: "l.gan", body: "ލ. ގަން" },
{ id: "l.hithadhoo", body: "ލ. ހިތަދޫ" },
{ id: "l.isdhoo", body: "ލ. އިސްދޫ" },
{ id: "l.kalaidhoo", body: "ލ. ކަލައިދޫ" },
{ id: "l.kunahandhoo", body: "ލ. ކުނަހަންދޫ" },
{ id: "l.maabaidhoo", body: "ލ. މާބައިދޫ" },
{ id: "l.maamendhoo", body: "ލ. މާމެންދޫ" },
{ id: "l.maavah", body: "ލ. މާވަށް" },
{ id: "l.mundoo", body: "ލ. މުންޑޫ" },
{ id: "lh.hinnavaru", body: "ޅ. ހިންނަވަރު" },
{ id: "lh.kurendhoo", body: "ޅ. ކުރެންދޫ" },
{ id: "lh.naifaru", body: "ޅ. ނައިފަރު" },
{ id: "lh.olhuvelifushi", body: "ޅ. އޮޅުވެލިފުށި" },
{ id: "m.dhiggaru", body: "މ. ދިއްގަރު" },
{ id: "m.kolhufushi", body: "މ. ކޮޅުފުށި" },
{ id: "m.maduvvari", body: "މ. މަޑުއްވަރި" },
{ id: "m.mulah", body: "މ. މުލައް" },
{ id: "m.muli", body: "މ. މުލި" },
{ id: "m.naalaafushi", body: "މ. ނާލާފުށި" },
{ id: "m.raiymandhoo", body: "މ. ރަތްމަންދޫ" },
{ id: "m.veyvah", body: "މ. ވޭވަށް" },
{ id: "n.fohdhoo", body: "ނ. ފޮއްދޫ" },
{ id: "n.henbadhoo", body: "ނ. ހެނބަދޫ" },
{ id: "n.holhudhoo", body: "ނ. ހޮޅުދޫ" },
{ id: "n.kendhikulhudhoo", body: "ނ. ކެނދިކުޅުދޫ" },
{ id: "n.kudafari", body: "ނ. ކުޑަފަރި" },
{ id: "n.landhoo", body: "ނ. ލަންދޫ" },
{ id: "n.lhohi", body: "ނ. ޅޮހި" },
{ id: "n.maafaru", body: "ނ. މާފަރު" },
{ id: "n.maalhendhoo", body: "ނ. މާޅެންދޫ" },
{ id: "n.magoodhoo", body: "ނ. މަގޫދޫ" },
{ id: "n.manadhoo", body: "ނ. މަނަދޫ" },
{ id: "n.miladhoo", body: "ނ. މިލަދޫ" },
{ id: "n.velidhoo", body: "ނ. ވެލިދޫ" },
{ id: "r.alifushi", body: "ރ. އަލިފުށި" },
{ id: "r.angolhitheemu", body: "ރ. އަނގޮޅިތީމު" },
{ id: "r.dhuvaafaru", body: "ރ. ދުވާފަރު" },
{ id: "r.fainu", body: "ރ. ފައިނު" },
{ id: "r.hulhudhuffaaru", body: "ރ. ހުޅުދުއްފާރު" },
{ id: "r.inguraidhoo", body: "ރ. އިނގުރައިދޫ" },
{ id: "r.innamaadhoo", body: "ރ. އިންނަމާދޫ" },
{ id: "r.kandholhudhoo", body: "ރ. ކަނދޮޅުދޫ" },
{ id: "r.kinolhas", body: "ރ. ކިނޮޅަސް" },
{ id: "r.maakurathu", body: "ރ. މާކުރަތު" },
{ id: "r.maduvvari", body: "ރ. މަޑުއްވަރި" },
{ id: "r.meedhoo", body: "ރ. މީދޫ" },
{ id: "r.rasgetheemu", body: "ރ. ރަސްގެތީމު" },
{ id: "r.rasmaadhoo", body: "ރ. ރަސްމާދޫ" },
{ id: "r.ungoofaaru", body: "ރ. އުނގޫފާރު" },
{ id: "r.vaadhoo", body: "ރ. ވާދޫ" },
{ id: "sh.feevah", body: "ށ. ފީވައް" },
{ id: "sh.bileiyfahi", body: "ށ. ބިލެތްފަހި" },
{ id: "sh.feydhoo", body: "ށ. ފޭދޫ" },
{ id: "sh.foakaidhoo", body: "ށ. ފޯކައިދޫ" },
{ id: "sh.funadhoo", body: "ށ. ފުނަދޫ" },
{ id: "sh.goidhoo", body: "ށ. ގޮއިދޫ" },
{ id: "sh.kanditheemu", body: "ށ. ކަނޑިތީމު" },
{ id: "sh.komandoo", body: "ށ. ކޮމަންޑޫ" },
{ id: "sh.lhaimagu", body: "ށ. ޅައިމަގު" },
{ id: "sh.maaungoodhoo", body: "ށ. މާއުނގޫދޫ" },
{ id: "sh.maroshi", body: "ށ. މަރޮށި" },
{ id: "sh.milandhoo", body: "ށ. މިލަންދޫ" },
{ id: "sh.narudhoo", body: "ށ. ނަރުދޫ" },
{ id: "sh.noomaraa", body: "ށ. ނޫމަރާ" },
{ id: "th.burunee", body: "ތ. ބުރުނި" },
{ id: "th.dhiyamigili", body: "ތ. ދިޔަމިގިލި" },
{ id: "th.gaadhiffushi", body: "ތ. ގާދިއްފުށި" },
{ id: "th.guraidhoo", body: "ތ. ގުރައިދޫ" },
{ id: "th.hirilandhoo", body: "ތ. ހިރިލަންދޫ" },
{ id: "th.kandoodhoo", body: "ތ. ކަނޑޫދޫ" },
{ id: "th.kinbidhoo", body: "ތ. ކިނބިދޫ" },
{ id: "th.madifushi", body: "ތ. މަޑިފުށި" },
{ id: "th.omadhoo", body: "ތ. އޮމަދޫ" },
{ id: "th.thimarafushi", body: "ތ. ތިމަރަފުށި" },
{ id: "th.vandhoo", body: "ތ. ވަންދޫ" },
{ id: "th.veymandoo", body: "ތ. ވޭމަންޑޫ" },
{ id: "th.vilufushi", body: "ތ. ވިލުފުށި" },
{ id: "v.felidhoo", body: "ވ. ފެލިދޫ" },
{ id: "v.fulidhoo", body: "ވ. ފުލިދޫ" },
{ id: "v.keyodhoo", body: "ވ. ކެޔޮދޫ" },
{ id: "v.rakeedhoo", body: "ވ. ރަކީދޫ" },
{ id: "v.thinadhoo", body: "ވ. ތިނަދޫ" }]

export const atolls = [{ id: "nomatter", body: "ކޮންމެ އަތޮޅެއްވިޔަސް އޯކޭ" },
{ id: "malecity", body: "މާލެ ސިޓީ" },
{ id: "fuvahmulahcity", body: "ފުވައްމުލައް ސިޓީ" },
{ id: "adducity", body: "އައްޑޫ ސިޓީ" },
{ id: "kulhudhuffushicity", body: "ކުޅުދުއްފުށި ސިޓީ" },
{ id: "aa", body: "އއ" },
{ id: "adh", body: "އދ" },
{ id: "b", body: "ބ" },
{ id: "dh", body: "ދ" },
{ id: "f", body: "ފ" },
{ id: "ga", body: "ގއ" },
{ id: "gdh", body: "ގދ" },
{ id: "ha", body: "ހއ" },
{ id: "hdh", body: "ހދ" },
{ id: "k", body: "ކ" },
{ id: "l", body: "ލ" },
{ id: "lh", body: "ޅ" },
{ id: "m", body: "މ" },
{ id: "n", body: "ނ" },
{ id: "r", body: "ރ" },
{ id: "sh", body: "ށ" },
{ id: "th", body: "ތ" },
{ id: "v", body: "ވ" }]