export const userFields = [
  {
    title: "User Name",
    type: "text",
    name: "username",
    placeholder: "username",
    changable: 1,
    required: 1,
  },
  {
    title: "Email",
    type: "text",
    name: "email",
    placeholder: "email",
    changable: 1,
    required: 1,
  },
  {
    title: "current Address",
    type: "text",
    name: "currentaddress",
    placeholder: "currentaddress",
    changable: 1,
    required: 1,
  },
  {
    title: "currentisland",
    type: "select",
    name: "currentisland",
    placeholder: "currentisland",
    changable: 1,
    required: 1,
  },
  {
    title: "dob",
    type: "date",
    name: "dob",
    placeholder: "dob",
    changable: 1,
    required: 1,
  },
  {
    title: "gender",
    type: "select",
    name: "gender",
    placeholder: "gender",
    changable: 1,
    required: 1,
  },
  {
    title: "nid",
    type: "text",
    name: "nid",
    placeholder: "nid",
    changable: 1,
    required: 1,
  },
  {
    title: "profilePic",
    type: "text",
    name: "profilePic",
    placeholder: "profilePic",
    changable: 1,
    required: 1,
  },
  {
    title: "isProfilePublic",
    type: "select",
    name: "isProfilePublic",
    placeholder: "isProfilePublic",
    changable: 1,
    required: 1,
  },
];

export const userProfileFields = [
  {
    title: "Nick Name",
    type: "text",
    name: "nickname",
    placeholder: "nickname",
    changable: 1,
    required: 1,
  },
  {
    title: "Living In",
    type: "text",
    name: "livingin",
    placeholder: "livingin",
    changable: 1,
    required: 1,
  },
  {
    title: "About Me",
    type: "textarea",
    name: "aboutme",
    placeholder: "aboutme",
    changable: 1,
    required: 1,
  },
];

const myProfileFields = [
  { label: "id", key: "id", val: 7 },
  { label: "createdAt", key: "createdAt", val: "2023-12-22T19:00:00.000Z" },
  { label: "publishedAt", key: "publishedAt", val: null },
  { label: "userId", key: "userId", val: 40 },
  { label: "nickname", key: "nickname", val: "Haifa" },
  { label: "livingIn", key: "livingIn", val: "male city" },
  { label: "aboutme", key: "aboutme", val: "އަހަރެންނާމެދު ބުނާނީ" },
  { label: "photo", key: "photo", val: "" },
  { label: "education", key: "education", val: "" },
  { label: "job", key: "job", val: "ވަޒީފާ އަދާކުރަން" },
  { label: "salary", key: "salary", val: "" },
  {
    label: "willing2relocate",
    key: "willing2relocate",
    val: "އަދި ވަކިގޮތެއް ނުނިންމޭ",
  },
  { label: "profilepostedby", key: "profilepostedby", val: "އަމިއްލައަށް" },
  { label: "maritalstatus", key: "maritalstatus", val: "" },
  { label: "noofmarriages", key: "noofmarriages", val: "" },
  { label: "children", key: "children", val: "" },
  { label: "kids_staying_at", key: "kids_staying_at", val: "" },
  { label: "like_to_have_children", key: "like_to_have_children", val: "" },
  { label: "polygyny", key: "polygyny", val: "" },
  { label: "health", key: "health", val: "" },
  { label: "pray", key: "pray", val: "" },
  { label: "languages", key: "languages", val: "" },
  { label: "origin", key: "origin", val: "" },
  { label: "haircolor", key: "haircolor", val: "" },
  { label: "bodytype", key: "bodytype", val: "" },
  { label: "height", key: "height", val: "" },
  { label: "dresscode", key: "dresscode", val: "" },
  { label: "l4_atoll", key: "l4_atoll", val: "" },
  { label: "l4_island", key: "l4_island", val: "" },
  { label: "l4_age_range_start", key: "l4_age_range_start", val: "" },
  { label: "l4_age_range_end", key: "l4_age_range_end", val: "" },
  { label: "l4_willing2relocate", key: "l4_willing2relocate", val: "" },
  { label: "l4_maritalstatus", key: "l4_maritalstatus", val: "" },
  { label: "l4_children", key: "l4_children", val: "" },
  { label: "l4_kids_staying_at", key: "l4_kids_staying_at", val: "" },
  {
    label: "l4_like_to_have_children",
    key: "l4_like_to_have_children",
    val: "",
  },
  { label: "l4_poligyny", key: "l4_poligyny", val: "" },
  { label: "l4_languages", key: "l4_languages", val: "" },
  { label: "l4_pray", key: "l4_pray", val: "" },
  { label: "l4_origin", key: "l4_origin", val: "" },
  { label: "l4_haircolor", key: "l4_haircolor", val: "" },
  { label: "l4_bodytype", key: "l4_bodytype", val: "" },
  { label: "l4_height", key: "l4_height", val: "" },
  { label: "l4_dresscode", key: "l4_dresscode", val: "" },
  { label: "l4_profession", key: "l4_profession", val: "" },
  {
    label: "l4_minimum_qualification",
    key: "l4_minimum_qualification",
    val: "",
  },
  { label: "l4_other", key: "l4_other", val: "" },
];
