import { atolls, islands } from "./databases";

export const profileFormFildsAll = [
  {
    label: "nickname",
    category: "profile_basics",
    step: "part1",
    tab: "own",
    need: "yes",
    id: "nickname",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ޕޯސްޓުން ފެންނަން ބޭނުންފުޅުވާ ނަން",
    obj: ""
  },

  {
    label: "livingIn",
    category: "profile_basics",
    step: "part1",
    tab: "own",
    need: "yes",
    id: "livingIn",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: " ދިރިއުޅޭ ތަން ",
    obj: ""
  },
  {
    label: "aboutme",
    category: "profile_basics",
    step: "part1",
    tab: "own",
    need: "yes",
    id: "aboutme",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "އަހަރެންނާމެދު ބުނާނީ",
    obj: ""
  },
  {
    label: "Photo / Selfie",
    category: "register_basic",
    step: "part2",
    tab: "own",
    need: "no",
    id: "photo",
    view: "yes",
    require: "",
    type: "image",
    dir: "ltr",
    label_dv: "ފޮޓޯ / ސެލްފީއެއް",
    obj: ""
  },
  {
    label: "education",
    category: "profile_basics",
    step: "part2",
    tab: "own",
    need: "yes",
    id: "education",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ތަޢުލީމީ ފެންވަރު",
    obj: ""
  },
  {
    label: "job",
    category: "profile_basics",
    step: "part2",
    tab: "own",
    need: "yes",
    id: "job",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "ވަޒީފާ",
    obj: [{ id: 1, body: "ވަޒީފާ އަދާކުރަން" }, { id: 2, body: "ވަޒީީފާ އަދާނުކުރަން" }, { id: 3, body: "އަމިއްލަ ވިޔަފާރި" }, { id: 4, body: "މަސްވެރިކަން" }, { id: 5, body: "ދަނޑުވެރިކަން" }, { id: 6, body: "ކިޔަވައިދިނުން" }]
  },
  {
    label: "salary",
    category: "profile_basics",
    step: "part2",
    tab: "own",
    need: "yes",
    id: "salary",
    view: "yes",
    require: "",
    type: "text",
    dir: "ltr",
    label_dv: "މުސާރަ",
    obj: ""
  },
  {
    label: "willing2relocate",
    category: "profile_basics",
    step: "part2",
    tab: "own",
    need: "yes",
    id: "willing2relocate",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "އެހެން ރަށަކަން ބަދަލުވާން އޯކޭތޯ؟",
    obj: [{ id: 2, body: "އަދި ވަކިގޮތެއް ނުނިންމޭ" }, { id: 3, body: "މައްސަލައެއް ނެތް" }, { id: 4, body: "ބޭނުން" }, { id: 5, body: "ބޭނުމެއް ނޫން" }]
  },
  {
    label: "profilepostedby",
    category: "profile_basics",
    step: "part1",
    tab: "own",
    need: "yes",
    id: "profilepostedby",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "ޕޯޯސްޓް ޖަހަނީ...",
    obj: [{ id: 1, body: "ބެލެނިވެރިޔާ" }, { id: 2, body: "އަމިއްލައަށް" }]
  },
  {
    label: "maritalstatus",
    category: "kaiveni",
    step: "part2",
    tab: "own",
    need: "yes",
    id: "maritalstatus",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "ކައިވެނީގެ ޙާލަތު",
    obj: [{ id: 1, body: "އަލަށްވެސް ކައިވެނި ނުކުރަން" }, { id: 2, body: "ވަރިވެފައި" }, { id: 3, body: "ކައިވެނި ކޮށްގެން" }, { id: 4, body: "ދެއަތްބަށް އިނދެގެން" }]
  },
  {
    label: "noofmarriages",
    category: "kaiveni",
    step: "part2",
    tab: "own",
    need: "yes",
    id: "noofmarriages",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "މިހާތަނަށް ކޮށްފައިވާ ކައިވެނީގެ ޢަދަދު",
    obj: [{ id: 2, body: "އަލަށްވެސް ކައިވެނި ނުކުރަން" }, { id: 3, body: 1 }, { id: 4, body: 2 }, { id: 5, body: 3 }, { id: 6, body: 4 }, { id: 7, body: 5 }, { id: 8, body: 6 }, { id: 9, body: 7 }, { id: 10, body: 8 }]
  },
  {
    label: "children",
    category: "kaiveni",
    step: "part2",
    tab: "own",
    need: "yes",
    id: "children",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "ދަރިން",
    obj: [{ id: 2, body: "ދަރިއެއް ނެތް" }, { id: 3, body: 1 }, { id: 4, body: 2 }, { id: 5, body: 3 }, { id: 6, body: 4 }, { id: 7, body: 5 }, { id: 8, body: 6 }, { id: 9, body: 7 }, { id: 10, body: 8 }]
  },
  {
    label: "kids_staying_at",
    category: "kaiveni",
    step: "part2",
    tab: "own",
    need: "yes",
    id: "kids_staying_at",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "ދަރިިން ތިބެނީ",
    obj: [{ id: 1, body: "އަހަރެންގެ ގާތުގައި" }, { id: 2, body: "ދަރިންގެ މަންމަގެ ގާތުގައި" }, { id: 3, body: "ދަަރިންގެ މަންމަ ފަރާތު މާމަގެ ގާތުގައި" }, { id: 4, body: "ދަަރިންގެ ބައްޕަ ފަރާތު މާމަގެ ގާތުގައި" }, { id: 5, body: "ދަރިން ބޮޑުވެފައި" }]
  },
  {
    label: "like_to_have_children",
    category: "kaiveni",
    step: "part2",
    tab: "own",
    need: "yes",
    id: "like_to_have_children",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "އިތުރަށް ދަރިން ހޯދަން ބޭނުންތޯ؟",
    obj: [{ id: 2, body: "އަދި ވަކިގޮތެއް ނުނިންމޭ" }, { id: 3, body: "މައްސަލައެއް ނެތް" }, { id: 4, body: "ބޭނުން" }, { id: 5, body: "ބޭނުމެއް ނޫން" }]
  },
  {
    label: "polygyny",
    category: "kaiveni",
    step: "part2",
    tab: "own",
    need: "yes",
    id: "polygyny",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "އެއް އަތްބަށްވުރެ ގިނައިން ކައިވެނިކުރުމަށް އޯކޭތޯ؟",
    obj: [{ id: 2, body: "އަދި ވަކިގޮތެއް ނުނިންމޭ" }, { id: 3, body: "މައްސަލައެއް ނެތް" }, { id: 4, body: "ބޭނުން" }, { id: 5, body: "ބޭނުމެއް ނޫން" }]
  },
  {
    label: "health",
    category: "health",
    step: "part2",
    tab: "own",
    need: "yes",
    id: "health",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "ޞިއްޙަތު",
    obj: [{ id: 2, body: "ދުޅަހެޔޮ" }, { id: 3, body: "އާދައިގެ" }, { id: 4, body: "ނުކުޅެދޭ" }]
  },
  {
    label: "pray",
    category: "lifestyleNdStatus",
    step: "part2",
    tab: "own",
    need: "yes",
    id: "pray",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "ނަމާދާއި ތިބާއާއި އޮތް ގުޅުން",
    obj: [{ id: "ަalways", body: "އަބަދުވެސް ނަމާދުކުރަން" }, { id: "normally", body: "ޢާންމުކޮށް ނަމާދުކުރަން" }, { id: "sometimes", body: "ވަގުތުވެއްޖެއްޔާ ނަމާދުކުރަން" }, { id: "sometimes1", body: "ބައެއް ފަހަރު ނުކުރެވިދޭ" }, { id: "onlyfridayprayer", body: "ހަމައެކަނި ހުކުރުނަމާދުކުރަން" }, { id: "onlyramazaan", body: "ހަަމައެކަނި ރޯދަމަހުގައި ނަމާދުކުރަން" }, { id: "cant", body: "އެއްގޮތަކަށްވެސް ނުކުރެވޭ" }]
  },
  {
    label: "languages",
    category: "lifestyleNdStatus",
    step: "part2",
    tab: "own",
    need: "no",
    id: "languages",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ވާހަކަދެއްކޭ ބަހުރުވަ / ބަސްތައް",
    obj: ""
  },
  {
    label: "origin",
    category: "lifestyleNdStatus",
    step: "part2",
    tab: "own",
    need: "no",
    id: "origin",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "އަޞްލު / ނަސްލު",
    obj: ""
  },
  {
    label: "haircolor",
    category: "appearance",
    step: "part2",
    tab: "own",
    need: "no",
    id: "haircolor",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ބޮލުގެ އިސްތަށިގަނޑުގެ ކުލަ",
    obj: ""
  },
  {
    label: "bodytype",
    category: "appearance",
    step: "part2",
    tab: "own",
    need: "no",
    id: "bodytype",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ހަށިގަނޑާއިމެދު..",
    obj: ""
  },
  {
    label: "height",
    category: "appearance",
    step: "part2",
    tab: "own",
    need: "no",
    id: "height",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "އިސްކޮޅު",
    obj: ""
  },
  {
    label: "dresscode",
    category: "appearance",
    step: "part2",
    tab: "own",
    need: "no",
    id: "dresscode",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ހެދުންއެޅުމުގެ ވައްޓަފާޅި",
    obj: ""
  },
  {
    label: "l4_atoll",
    category: "profile_basics",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_atoll",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "އަތޮޅު",
    obj: atolls
  },
  {
    label: "l4_island",
    category: "profile_basics",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_island",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "ރަށް",
    obj: islands
  },
  {
    label: "l4_age_range_start",
    category: "profile_basics",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_age_range_start",
    view: "yes",
    require: "",
    type: "number",
    dir: "rtl",
    label_dv: "ބޮޭނުންވާ ޢުމުރުފުރާ ފެށޭ",
    obj: ""
  },
  {
    label: "l4_age_range_end",
    category: "profile_basics",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_age_range_end",
    view: "yes",
    require: "",
    type: "number",
    dir: "rtl",
    label_dv: "ބޮޭނުންވާ ޢުމުރުފުރާ ނިމޭ",
    obj: ""
  },
  {
    label: "l4_willing2relocate",
    category: "profile_basics",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_willing2relocate",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "އެހެން ރަށަކަން ބަދަލުވާން އޯކޭތޯ؟",
    obj: [{ id: "nomatter", body: "ޝަރުޠެއް ނެތް" }, { id: 2, body: "އަދި ވަކިގޮތެއް ނުނިންމޭ" }, { id: 3, body: "މައްސަލައެއް ނެތް" }, { id: 4, body: "ބޭނުން" }, { id: 5, body: "ބޭނުމެއް ނޫން" }]
  },
  {
    label: "l4_maritalstatus",
    category: "lifestyleNdStatus",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_maritalstatus",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "ކައިވެނީގެ ޙާލަތު",
    obj: [{ id: "nomatter", body: "ޝަރުޠެއް ނެތް" }, { id: 1, body: "އަލަށްވެސް ކައިވެނި ނުކުރަން" }, { id: 2, body: "ވަރިވެފައި" }, { id: 3, body: "ކައިވެނި ކޮށްގެން" }, { id: 4, body: "ދެއަތްބަށް އިނދެގެން" }, { id: "", body: "" }, { id: "", body: "" }, { id: "", body: "" }, { id: "", body: "" }]
  },
  {
    label: "l4_noofmarriages",
    category: "lifestyleNdStatus",
    step: "part3",
    tab: "details",
    need: "no",
    id: "l4_noofmarriages",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "މިހާތަނަށް ކޮށްފައިވާ ކައިވެނީގެ ޢަދަދު",
    obj: [{ id: "nomatter", body: "ޝަރުޠެއް ނެތް" }, { id: 2, body: "އަލަށްވެސް ކައިވެނި ނުކުރަން" }, { id: 3, body: 1 }, { id: 4, body: 2 }, { id: 5, body: 3 }, { id: 6, body: 4 }, { id: 7, body: 5 }, { id: 8, body: 6 }, { id: 9, body: 7 }, { id: 10, body: 8 }]
  },
  {
    label: "l4_children",
    category: "lifestyleNdStatus",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_children",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "ދަރިން",
    obj: ""
  },
  {
    label: "l4_kids_staying_at",
    category: "lifestyleNdStatus",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_kids_staying_at",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "ދަރިިން ތިބެނީ",
    obj: [{ id: "nomatter", body: "ޝަރުޠެއް ނެތް" }, { id: 1, body: "އަހަރެންގެ ގާތުގައި" }, { id: 2, body: "ދަރިންގެ މަންމަގެ ގާތުގައި" }, { id: 3, body: "ދަަރިންގެ މަންމަ ފަރާތު މާމަގެ ގާތުގައި" }, { id: 4, body: "ދަަރިންގެ ބައްޕަ ފަރާތު މާމަގެ ގާތުގައި" }, { id: 5, body: "ދަރިން ބޮޑުވެފައި" }, { id: "", body: "" }, { id: "", body: "" }, { id: "", body: "" }]
  },
  {
    label: "l4_like_to_have_children",
    category: "lifestyleNdStatus",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_like_to_have_children",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "އިތުރަށް ދަރިން ހޯދަން ބޭނުންތޯ؟",
    obj: [{ id: 2, body: "އަދި ވަކިގޮތެއް ނުނިންމޭ" }, { id: 3, body: "މައްސަލައެއް ނެތް" }, { id: 4, body: "ބޭނުން" }, { id: 5, body: "ބޭނުމެއް ނޫން" }]
  },
  {
    label: "l4_poligyny",
    category: "lifestyleNdStatus",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_poligyny",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "އެއް އަތްބަށްބުރެ ގިނައިން ކައިވެނިކުރުމަށް އޯކޭތޯ؟",
    obj: [{ id: 2, body: "އަދި ވަކިގޮތެއް ނުނިންމޭ" }, { id: 3, body: "މައްސަލައެއް ނެތް" }, { id: 4, body: "ބޭނުން" }, { id: 5, body: "ބޭނުމެއް ނޫން" }]
  },
  {
    label: "l4_languages",
    category: "lifestyleNdStatus",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_languages",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ވާހަކަދެއްކޭ ބަހުރުވަ / ބަސްތައް",
    obj: ""
  },
  {
    label: "l4_pray",
    category: "lifestyleNdStatus",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_pray",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ނަމާދާއި ތިބާއާއި އޮތް ގުޅުން",
    obj: ""
  },
  {
    label: "l4_origin",
    category: "appearance",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_origin",
    view: "yes",
    require: "",
    type: "select",
    dir: "rtl",
    label_dv: "އަޞްލު / ނަސްލު",
    obj: ""
  },
  {
    label: "l4_haircolor",
    category: "appearance",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_haircolor",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ބޮލުގެ އިސްތަށިގަނޑުގެ ކުލަ",
    obj: ""
  },
  {
    label: "l4_bodytype",
    category: "appearance",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_bodytype",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ހަށިގަނޑާއިމެދު..",
    obj: ""
  },
  {
    label: "l4_height",
    category: "appearance",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_height",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "އިސްކޮޅު",
    obj: ""
  },
  {
    label: "l4_dresscode",
    category: "appearance",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_dresscode",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ހެދުންއެޅުމުގެ ވައްޓަފާޅި",
    obj: ""
  },
  {
    label: "l4_profession",
    category: "postInput",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_profession",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ވަޒީފާ",
    obj: ""
  },
  {
    label: "l4_minimum_qualification",
    category: "postInput",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_minimum_qualification",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ތަޢުލީމީ ފެންވަރު",
    obj: ""
  },
  {
    label: "l4_other",
    category: "postInput",
    step: "part3",
    tab: "lookingfor",
    need: "no",
    id: "l4_other",
    view: "yes",
    require: "",
    type: "text",
    dir: "rtl",
    label_dv: "ފާހަނގަކުރަން ބޭނުންވާ އެހެންކަމެއް އޮތްނަމަ ހިމަނުއްވާ",
    obj: ""
  },
]